---
apiVersion: v1
kind: Secret
metadata:
  name: yelp-camp-secrets
type: Opaque
data:
  CLOUDINARY_CLOUD_NAME: ZGhxdnlyMXZo
  CLOUDINARY_KEY: MzIyNjMyMjY4NTU1MzQz
  CLOUDINARY_SECRET: NnQ0a28xb1VWUW55MEpuTnZra19vYkRaZlVh
  MAPBOX_TOKEN: cGsuZXlKMUlqb2lhV0Z0WldabGJXVnVZU0lzSW1FaU9pSmpiV1UzTkRRNE1XMHdNSEF4TW10eU16WXhPWFV6YW5WeUluMC5tZnUtZHZVdy1FSGc2VHFNbDBfLXRn
  DB_URL: bW9uZ29kYitzcnY6Ly9pc2FhY2VmZW1lbmEyMzpQYTEyMEFFd01IY1R2WUxsQGNsdXN0ZXIwLndlajFhcm0ubW9uZ29kYi5uZXQvP3JldHJ5V3JpdGVzPXRydWUmdz1tYWpvcml0eSZhcHBOYW1lPUNsdXN0ZXIw
  SECRET: SWFtZWZlbWVuYQ==

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: yelp-camp-deployment
  namespace: webapps
spec:
  replicas: 1
  selector:
    matchLabels:
      app: yelp-camp
  template:
    metadata:
      labels:
        app: yelp-camp
    spec:
      containers:
        - name: yelp-camp-container
          image: iamefe/dev:latest
          ports:
            - containerPort: 3000
          env:
            - name: CLOUDINARY_CLOUD_NAME
              valueFrom:
                secretKeyRef:
                  name: yelp-camp-secrets
                  key: CLOUDINARY_CLOUD_NAME
            - name: CLOUDINARY_KEY
              valueFrom:
                secretKeyRef:
                  name: yelp-camp-secrets
                  key: CLOUDINARY_KEY
            - name: CLOUDINARY_SECRET
              valueFrom:
                secretKeyRef:
                  name: yelp-camp-secrets
                  key: CLOUDINARY_SECRET
            - name: MAPBOX_TOKEN
              valueFrom:
                secretKeyRef:
                  name: yelp-camp-secrets
                  key: MAPBOX_TOKEN
            - name: DB_URL
              valueFrom:
                secretKeyRef:
                  name: yelp-camp-secrets
                  key: DB_URL
            - name: SECRET
              valueFrom:
                secretKeyRef:
                  name: yelp-camp-secrets
                  key: SECRET
          livenessProbe:
            httpGet:
              path: /
              port: 3000
            initialDelaySeconds: 30
          readinessProbe:
            httpGet:
              path: /
              port: 3000
            initialDelaySeconds: 30

---
apiVersion: v1
kind: Service
metadata:
  name: yelp-camp-service
  namespace: webapps
spec:
  selector:
    app: yelp-camp
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
  type: LoadBalancer
